recursive: true
require:
  - 'esm'
  - 'ts-node/register'
  - 'source-map-support/register'
package: './package.json'
reporter: 'mocha-multi-reporters'
reporter-option:
  - 'configFile=mocha-multi-reporters-config.json'
extension:
  - 'ts'
spec: 'src/test/ts/**/*.ts'
